# SPDX-License-Identifier: MIT OR GPL-3.0-or-later
---
name: lint

permissions: {}

on:
  pull_request:
    types: [opened, synchronize, reopened, ready_for_review, labeled]
  push:
  workflow_dispatch:

jobs:
  format:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - run: ./Tool/format.ps1
      - run: git diff --exit-code

  super-linter:
    runs-on: ubuntu-24.04
    permissions:
      contents: read
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - name: Super-Linter
        run: ./Tool/super-linter.sh -e SAVE_SUPER_LINTER_SUMMARY=false
